name: Проверка Node.js

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Установка Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Проверка версии Node.js
      run: node --version
    - name: Проверка структуры файлов
      run: ls -la
    - name: Переход в папку notes
      run: cd notes && ls -la
    - name: Проверка синтаксиса index.js
      run: node -c notes/index.js
